const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  PUSH_MESSAGE: "PUSH_MESSAGE",
};

export default ACTIONS;

export const GET_AGRICULTURAL = "GET_AGRICULTURAL";
export const CREATE_AGRICULTURAL = "CREATE_AGRICULTURAL";
export const UPDATE_AGRICULTURAL = "UPDATE_AGRICULTURAL";
export const DELETE_AGRICULTURAL = "DELETE_AGRICULTURAL";
