const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
};

export default ACTIONS;

export const GET_AGRICULTURAL = "GET_AGRICULTURAL";
export const CREATE_AGRICULTURAL = "CREATE_AGRICULTURAL";
export const UPDATE_AGRICULTURAL = "UPDATE_AGRICULTURAL";
export const DELETE_AGRICULTURAL = "DELETE_AGRICULTURAL";

export const GET_POST = "GET_POST";
export const GET_ALL_POST = "GET_ALL_POST";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
