const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
};

export default ACTIONS;

export const GET_AGRICULTURAL = "GET_AGRICULTURAL";
export const CREATE_AGRICULTURAL = "CREATE_AGRICULTURAL";
