GET http://localhost:4000/

###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "nhutanh",
  "password": "1234567"
}

###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "nhutanh",
  "password": "1234567",
  "email": "nhutanh1120@gmail.com"
}

### 
POST http://localhost:4000/api/auth/activation
Content-Type: application/json

{
  "activation_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5odXRhbmgiLCJwYXNzd29yZCI6IiQyYiQxMiQvL2FYV1JXTVJScEhGOUpMMzBBRGlPUlRWZGlFR0FBYzBoV1d5RGpNbUFmaVVmWEpuTzhSZSIsImVtYWlsIjoibmh1dGFuaDExMjBAZ21haWwuY29tIiwiaWF0IjoxNjI5NTQ2Mzg3LCJleHAiOjE2Mjk1NDY2ODd9.Y7g8Q_tnlPLCRVFq7wvWTMLDYt11kQuaYcf4GkwF5vQ"
}

### 
POST http://localhost:4000/api/auth/refresh_token

### 
POST http://localhost:4000/api/auth/forgot
Content-Type: application/json

{
  "email": "nhutanh1120@gmail.com"
}

###
GET http://localhost:4000/api/auth/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlN2VlMjFiMDA5Mjk2MGRiNGJhYiIsImlhdCI6MTYzMTI4OTE0MCwiZXhwIjoxNjMxODkzOTQwfQ.JVc3OCy36lst9EALrBpW6i-gvO-zXmNFQTVC11Ppqdk

###
GET http://localhost:4000/api/auth/all_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlN2VlMjFiMDA5Mjk2MGRiNGJhYiIsImlhdCI6MTYzMDk1ODgxNywiZXhwIjoxNjMxNTYzNjE3fQ.A9vykeICBuIUbH-Pay4w-jwXz9xcn8bev0c-BR_04Q0

###
GET http://localhost:4000/api/auth/logout

###
PATCH  http://localhost:4000/api/auth/update_role/6120e7ee21b0092960db4bab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlN2VlMjFiMDA5Mjk2MGRiNGJhYiIsImlhdCI6MTYyOTU2MzQ5MCwiZXhwIjoxNjMwMTY4MjkwfQ.M2sk3LRP5_g-2qMq__LOcgjpXpavvCzH9cLe_0uyp-4
