GET http://localhost:4000/api/post/all

###
GET http://localhost:4000/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTYzMjMyMywiZXhwIjoxNjM2MjM3MTIzfQ.17FdA37SlukN9t3RKseG8nP6bKdPw8eR88KH3y8aQH8

###
POST http://localhost:4000/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTYzMjMyMywiZXhwIjoxNjM2MjM3MTIzfQ.17FdA37SlukN9t3RKseG8nP6bKdPw8eR88KH3y8aQH8

{
  "title": "bai 2", 
  "description": "b",
  "attachment": "c"
}

###
PUT  http://localhost:4000/api/post/617dc53170245d55afcd15e2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTYzMjMyMywiZXhwIjoxNjM2MjM3MTIzfQ.17FdA37SlukN9t3RKseG8nP6bKdPw8eR88KH3y8aQH8

{
  "title": "update vue",
  "description": "update b"
}

###
DELETE  http://localhost:4000/api/post/617dc53170245d55afcd15e2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTYzMjMyMywiZXhwIjoxNjM2MjM3MTIzfQ.17FdA37SlukN9t3RKseG8nP6bKdPw8eR88KH3y8aQH8
