GET http://localhost:4000/api/post/all

###
GET http://localhost:4000/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTc0MTMwNCwiZXhwIjoxNjM2MzQ2MTA0fQ.W711x1Ic_bltW6pgMrfa_bndXDC5AZUi9sd7yqJuMq8

###
POST http://localhost:4000/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNjk1MTY1MCwiZXhwIjoxNjM3NTU2NDUwfQ.e2KF5daQZXrd8NULBpejTP8qv9ZwDj6bel_QuRsLeAU

{
  "title": "bai 3", 
  "description": "b",
  "tags": ["asds"],
  "attachment": "c"
}

###
PUT  http://localhost:4000/api/post/617dc53170245d55afcd15e2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTc0MTMwNCwiZXhwIjoxNjM2MzQ2MTA0fQ.W711x1Ic_bltW6pgMrfa_bndXDC5AZUi9sd7yqJuMq8

{
  "title": "update vue",
  "description": "update b"
}

###
DELETE  http://localhost:4000/api/post/617dc53170245d55afcd15e2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTc0MTMwNCwiZXhwIjoxNjM2MzQ2MTA0fQ.W711x1Ic_bltW6pgMrfa_bndXDC5AZUi9sd7yqJuMq8

###
PATCH http://localhost:4000/api/post/617f6f15563e102895a895d4/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTc0MTMwNCwiZXhwIjoxNjM2MzQ2MTA0fQ.W711x1Ic_bltW6pgMrfa_bndXDC5AZUi9sd7yqJuMq8

###
PATCH http://localhost:4000/api/post/617f6f15563e102895a895d4/unlike
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNTc0MTMwNCwiZXhwIjoxNjM2MzQ2MTA0fQ.W711x1Ic_bltW6pgMrfa_bndXDC5AZUi9sd7yqJuMq8
