###
GET http://localhost:4000/api/profile/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQ3YTdiODZhZWI1NzBlNjJhMzAyYyIsImlhdCI6MTYzNjk1MjU2MywiZXhwIjoxNjM2OTUzNDYzfQ.TOwGWyjULYdFZD9jKrmuwYiCKW9XXs-GCHtftuVOpjA

###
GET http://localhost:4000/api/profile/all/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGI1ZWZmNjY3ZmVmM2FjNGIyYWM4NiIsImlhdCI6MTYzNDQwNzExMywiZXhwIjoxNjM1MDExOTEzfQ.n470bv_sQGeKTYK0rzy50gMjBIxd7o8jdGb10H60JrA

### 
PATCH http://localhost:4000/api/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGI1ZjZlNDg0NzY0MDc0OGJkOWM1ZiIsImlhdCI6MTYzNDQwNzAwNSwiZXhwIjoxNjM1MDExODA1fQ.qVSszaGowNBH9b9q9cEP5VXAMkxi3_JudGPF9ZEhtqU

{
    "forename": "Tran Anh Nhut",
    "surname": "Luu",
    "phone": "0399234016",
    "address": "Vinh long",
    "description": "abcd",
    "avatar": "abcd.jpg"
}
###
PATCH  http://localhost:4000/api/profile/role/update/614b5f6e4847640748bd9c5f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGI1ZWZmNjY3ZmVmM2FjNGIyYWM4NiIsImlhdCI6MTYzNDQwNzExMywiZXhwIjoxNjM1MDExOTEzfQ.n470bv_sQGeKTYK0rzy50gMjBIxd7o8jdGb10H60JrA

{
    "role": "1"
}

###
PATCH  http://localhost:4000/api/profile/access/update/614b5f6e4847640748bd9c5f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGI1ZWZmNjY3ZmVmM2FjNGIyYWM4NiIsImlhdCI6MTYzNDQwNzExMywiZXhwIjoxNjM1MDExOTEzfQ.n470bv_sQGeKTYK0rzy50gMjBIxd7o8jdGb10H60JrA

{
    "access": "1"
}