###
GET http://localhost:4000/api/profile/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGI1ZWZmNjY3ZmVmM2FjNGIyYWM4NiIsImlhdCI6MTYzMzIzOTMxNSwiZXhwIjoxNjMzMjQwMjE1fQ.OBzMPtjeFd6ba-tkQvMYNzGFZNFE18IcqkA2iy9kuz4

###
GET http://localhost:4000/api/profile/all_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlN2VlMjFiMDA5Mjk2MGRiNGJhYiIsImlhdCI6MTYzMDk1ODgxNywiZXhwIjoxNjMxNTYzNjE3fQ.A9vykeICBuIUbH-Pay4w-jwXz9xcn8bev0c-BR_04Q0

###
PATCH  http://localhost:4000/api/auth/update_role/6120e7ee21b0092960db4bab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlN2VlMjFiMDA5Mjk2MGRiNGJhYiIsImlhdCI6MTYyOTU2MzQ5MCwiZXhwIjoxNjMwMTY4MjkwfQ.M2sk3LRP5_g-2qMq__LOcgjpXpavvCzH9cLe_0uyp-4
