GET http://localhost:4000/

###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "nhutanh",
  "password": "1234567",
  "email": "nhutanh1120@gmail.com"
}
###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "1234567",
  "email": "nhutanh@gmail.com"
}
### 
POST http://localhost:4000/api/auth/activation
Content-Type: application/json

{
  "activation_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTIkcUQ5bEVNVzR4MTFPYmZHNDNsc09VT0N2ZzF0WXh4SWhzSFRRcXNCeUNEUTFqQ3VvaHdaeUciLCJlbWFpbCI6Im5odXRhbmhAZ21haWwuY29tIiwiaWF0IjoxNjMyMzI5NTY3LCJleHAiOjE2MzIzMjk4Njd9.jvaD-RQTbvJJmlOATnElmyQ5wvNotwkVVdH5ZMYdi_k"
}
###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "nhutanh",
  "password": "1234567"
}
###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234567"
}

### 
GET http://localhost:4000/api/auth/refresh

###
GET http://localhost:4000/api/auth/logout

### 
POST http://localhost:4000/api/auth/forgot
Content-Type: application/json

{
  "email": "nhutanh1120@gmail.com"
}
###
POST http://localhost:4000/api/auth/reset
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGI1ZWZmNjY3ZmVmM2FjNGIyYWM4NiIsImlhdCI6MTYzNDQwNDc1OSwiZXhwIjoxNjM1MDA5NTU5fQ.2ILdCxdrs_9P9I38dWJnpOh1OPY1lRuEG2INTw_MLKA

{
  "password": "1234567"
}
